### ISSUE TITLE
Params are not truly externalized

### ISSUE THREAD

**Issue by ricksbrown** [wso2/puppet-apim#79]
**Description:**
init.pp inherits from manifests.pp - the intent is to be able to modify parameters without forking the codebase (without editing a manifest under source control). In puppet this is typically achieved using hiera.

Unfortunately the manifests are written is such a way that does not allow us to override the parameters without editing your manifests. This defeats the purpose of attempting to externalize the parameters in the first place.

In previous versions this was catered for, [for example here](https://github.com/wso2/puppet-apim/blob/d11f3a96eef20bafa93de50f25d17ec77c736602/wso2am_runtime/manifests/init.pp#L20).
You will note the parameter list in the class definition - that allowed for default values to be overridden by hiera. 

You can see this pattern has been removed in later versions, [for example here](https://github.com/wso2/puppet-apim/blob/7c651c635d7468a92c3cb868cb0f579dab581485/modules/apim_store/manifests/init.pp#L19).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VimukthiPerera** [comment]
Fixed with https://github.com/wso2/puppet-apim/pull/136
