### ISSUE TITLE
Make install path configurable

### ISSUE THREAD

**Issue by ricksbrown** [wso2/puppet-apim#81]
**Description:**
Install path is hard-coded to `/usr/lib64/wso2/`

Could be externalized to allow for alternate installation locations?

Current code:
`$install_path = "/usr/lib64/wso2/${product}/${product_version}"`

Possible alternative:
`$install_path = "${install_dir}/${product}/${product_version}"`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Savidude** [comment]
Hi Rick,
Thank you very much for your suggestion. We are in the process of updating Puppet resources for WSO2 products. We will be externalizing the install path as suggested by you.

**Comment by Savidude** [comment]
This has been addressed by introducing a new parameter `$products_dir = "/usr/local/wso2"` to indicate the path in which the servers are installed.
