### ISSUE TITLE
custom.pp mostly useless?

### ISSUE THREAD

**Issue by ricksbrown** [wso2/puppet-apim#82]
**Description:**
custom.pp does not inherit the params for the profile in which it runs. It seems unlikely anyone can do much useful without this.

 It should probably inherit from the params class...?

**Comment by Savidude** [comment]
Hi Rick,

The purpose of custom.pp is to provide users with the ability to provide custom configurations to the module. Users could inherit the params class if required, or the custom class can be executed by itself.

Hope this addresses your concerns 🙂

**Comment by VimukthiPerera** [comment]
Please reopen if you have further questions
